Repository akafael/ufpe-project-bsg, pull requests merged in 2023-09, with the labels that each got.

#45 Added BSG_MOTOR function
  code/bsgcontrol.c
  code/test_bsg.c
Labels: enhancement

#56 Replace ifs inside bsgcontrol with getState functions related with each struct
  code/bsgcontrol.c
  code/vehicle.c
Labels: enhancement

#59 Add code documentation and configure Doxygen to generate documentation page
  .github/workflows/c-cpp.yml
  code/Doxyfile
  code/Makefile
  code/battery.h
  code/bsg.h
  code/bsgcontrol.c
  code/bsgcontrol.h
  code/calibration.c
  code/calibration.h
  code/csvutils.c
  code/csvutils.h
  code/engine.h
  code/test_csvutils.c
  code/vehicle.c
  code/vehicle.h
Labels: documentation

#75 Fix CI Badge link at README.md
  README.md
Labels: bug

#89 All IF's have now been replaced by ELSE IF and the final ELSE has bee…
  code/vehicle.c
Labels: enhancement

#97 Model Update
  models/battery_model.slx
  models/bsg_model.slx
  models/complete_model.slx
  models/engine_model.slx
  models/vehicle_model.slx
Labels: model

#104 Add two new test case to test_engine
  code/Makefile
  code/engine.c
  code/test_engine.c
  docs/gcovr/index.battery.c.997c77ee932e53d01e03f26f11eb10e0.html
  docs/gcovr/index.battery.c.html
  docs/gcovr/index.bsgcontrol.c.004e58185eab0e04690abe8ab893d306.html
  docs/gcovr/index.bsgcontrol.c.html
  docs/gcovr/index.css
  docs/gcovr/index.csvutils.c.f705ebf3a87d8f879e7064dfe19b3ae6.html
  docs/gcovr/index.csvutils.c.html
  docs/gcovr/index.engine.c.1a5ba8aa64b09297cf411db581d59b89.html
  docs/gcovr/index.engine.c.html
  docs/gcovr/index.html
  docs/gcovr/index.vehicle.c.6087cbb30b0a88af4bd7ea8bfd0ed6ad.html
  docs/gcovr/index.vehicle.c.html
  docs/lcov/code/battery.c.func-sort-c.html
  docs/lcov/code/battery.c.func.html
  docs/lcov/code/battery.c.gcov.html
  docs/lcov/code/bsgcontrol.c.func-sort-c.html
  docs/lcov/code/bsgcontrol.c.func.html
  docs/lcov/code/bsgcontrol.c.gcov.html
  docs/lcov/code/csvutils.c.func-sort-c.html
  docs/lcov/code/csvutils.c.func.html
  docs/lcov/code/csvutils.c.gcov.html
  docs/lcov/code/engine.c.func-sort-c.html
  docs/lcov/code/engine.c.func.html
  docs/lcov/code/engine.c.gcov.html
  docs/lcov/code/index-sort-b.html
  docs/lcov/code/index-sort-f.html
  docs/lcov/code/index-sort-l.html
  docs/lcov/code/index.html
  docs/lcov/code/vehicle.c.func-sort-c.html
  docs/lcov/code/vehicle.c.func.html
  docs/lcov/code/vehicle.c.gcov.html
  docs/lcov/coverage.info
  docs/lcov/index-sort-b.html
  docs/lcov/index-sort-f.html
  docs/lcov/index-sort-l.html
  docs/lcov/index.html
Labels: bug

#102 Move makefile to root folder and fix shared lib build
  .github/workflows/c-cpp.yml
  Makefile
  README.md
  code/libbsg.h
Labels: enhancement

#101 Create gitpages action to deploy documentation automaticaly
  .github/workflows/gitpages.yml
Labels: documentation

#110 Update README.md
  README.md
Labels: documentation

#114 Update README.md
  README.md
Labels: documentation
